CREATE OR REPLACE TRIGGER TMWIN.DOCUMENT_FILES_AUDIT_TRIGGER_UPDATE
AFTER UPDATE OF FILE_PATH ON TMWIN.DOCUMENT_FILES
REFERENCING NEW AS NEW_ENTRY
FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
   IF EXISTS (SELECT * FROM TMWIN.DOCUMENT_FILES_USERS_AUDIT WHERE DOCUMENT_FILES_ID = NEW_ENTRY.ID) THEN
      UPDATE TMWIN.DOCUMENT_FILES_USERS_AUDIT SET USERNAME = USER WHERE DOCUMENT_FILES_ID = NEW_ENTRY.ID;   
   ELSE
      INSERT INTO TMWIN.DOCUMENT_FILES_USERS_AUDIT (DOCUMENT_FILES_ID, USERNAME) VALUES (NEW_ENTRY.ID, USER);
   END IF;
END