CREATE OR REPLACE TRIGGER TMWIN.DOCUMENT_FILES_AUDIT_TRIGGER_INSERT
  AFTER INSERT ON TMWIN.DOCUMENT_FILES
  referencing new as NEW_ENTRY
  for each ROW MODE DB2SQL
BEGIN ATOMIC
   INSERT INTO TMWIN.DOCUMENT_FILES_USERS_AUDIT (DOCUMENT_FILES_ID, USERNAME) VALUES (NEW_ENTRY.ID, USER);
END