CREATE TABLE TMWIN.DOCUMENT_FILES_USERS_AUDIT
( ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DOCUMENT_FILES_ID INTEGER,
  USERNAME VARCHAR(50),
  PRIMARY KEY(ID)
)